version: '3.9'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=db_rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local